version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: livraria-postgres
    environment:
      POSTGRES_DB: livraria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - livraria-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d livraria"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livraria-backend
    env_file:
      - docker.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/livraria?currentSchema=biblioteca
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET:-mt-secret-key-docker}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - livraria-network
    restart: unless-stopped

 
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: livraria-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@livraria.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - livraria-network
    restart: unless-stopped
    profiles:
      - tools

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    container_name: livraria-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - livraria-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  livraria-network:
    driver: bridge